config/routes.rb
Rails.application.routes.draw do
  # Sleeper Analytics routes
  resources :sleeper_analytics, only: [:index, :show] do
    collection do
      get :draft_analysis
      get :player_performance  
      get :team_performance
      get :transaction_analysis
      get :player_charts
      get :draft_spending_charts
    end
  end
  # Root route - home page
  root 'home#index'

  # Position-specific player routes
  get '/quarterbacks', to: 'players#index', defaults: { position: 'QB' }
  get '/running-backs', to: 'players#index', defaults: { position: 'RB' }
  get '/wide-receivers', to: 'players#index', defaults: { position: 'WR' }
  get '/tight-ends', to: 'players#index', defaults: { position: 'TE' }

  # Player detail routes by position
  get '/quarterbacks/:id', to: 'players#show', defaults: { position: 'QB' }
  get '/running-backs/:id', to: 'players#show', defaults: { position: 'RB' }
  get '/wide-receivers/:id', to: 'players#show', defaults: { position: 'WR' }
  get '/tight-ends/:id', to: 'players#show', defaults: { position: 'TE' }

  # Import routes
  resources :imports, only: [:index] do
    collection do
      get :pro_football_reference_player_stats
      post :import_pro_football_reference_stats
      post :bulk_import_pro_football_reference_stats
      get :sleeper_league_data
      post :import_sleeper_league_data
      post :bulk_import_sleeper_league_data
      get :sleeper_player_stats
      post :import_sleeper_player_stats
      post :bulk_import_sleeper_player_stats
      post :import_sleeper_players
    end
  end

  # Analytics routes - RESTful (keeping for backward compatibility)
  resources :analytics, only: [:index, :show] do
    collection do
      get :rankings  # /analytics/rankings
      get :teams     # /analytics/teams
    end
  end

  # Sidekiq monitoring (if you want to see background jobs)
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "Gridiron Guru", root_path, class: "navbar-brand fw-bold" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path,
              class: "nav-link #{'active' if current_page?(root_path)}" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
            Positions
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Quarterbacks", "/quarterbacks", class: "dropdown-item" %></li>
            <li><%= link_to "Running Backs", "/running-backs", class: "dropdown-item" %></li>
            <li><%= link_to "Wide Receivers", "/wide-receivers", class: "dropdown-item" %></li>
            <li><%= link_to "Tight Ends", "/tight-ends", class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
            Analytics
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Pro Football Reference", analytics_path, class: "dropdown-item" %></li>
            <li><%= link_to "Rankings", rankings_analytics_path, class: "dropdown-item" %></li>
            <li><%= link_to "Team Analysis", teams_analytics_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "🏈 Sleeper League Analytics", sleeper_analytics_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "Import Data", imports_path, 
              class: "nav-link #{'active' if current_page?(imports_path)}" %>
        </li>
      </ul>
      
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Sidekiq", "/sidekiq", class: "nav-link", target: "_blank" %>
        </li>
      </ul>
    </div>
  </div>
</nav>